name: Generate and Deploy Token Data

on:
  push:
    branches:
      - main  # main 브랜치로 푸시할 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. GitHub API에서 데이터 가져오기
      - name: Fetch data from API
        env:
          GITHUB_TOKEN: ${{ secrets.YEOSU_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user > data.json

      # 3. 결과를 Pages에서 사용할 수 있도록 커밋 및 푸시
      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json with API data"
          git push
